"""Shared enums and quality classifications used across engineering modules."""

from enum import Enum


class DataQuality(str, Enum):
    GOOD = "GOOD"
    ACCEPTABLE = "ACCEPTABLE"
    WARNING = "WARNING"
    POOR = "POOR"
    INVALID = "INVALID"


class ValidationStatus(str, Enum):
    VALID = "VALID"
    VALID_WITH_WARNINGS = "VALID_WITH_WARNINGS"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    NOT_VALIDATED = "NOT_VALIDATED"
    INVALID = "INVALID"


class ConsistencyStatus(str, Enum):
    CONSISTENT = "CONSISTENT"
    INCONSISTENT = "INCONSISTENT"
    UNVERIFIABLE = "UNVERIFIABLE"
    DATA_QUALITY_ISSUE = "DATA_QUALITY_ISSUE"


class Severity(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class SupportStatus(str, Enum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    NOT_VALIDATED = "NOT_VALIDATED"


class FaultType(str, Enum):
    AG = "AG"
    BG = "BG"
    CG = "CG"
    AB = "AB"
    BC = "BC"
    CA = "CA"
    ABG = "ABG"
    BCG = "BCG"
    CAG = "CAG"
    ABC = "ABC"
    ABCG = "ABCG"
    UNKNOWN = "UNKNOWN"


class ClassificationStatus(str, Enum):
    CLASSIFIED = "CLASSIFIED"
    PROBABLE = "PROBABLE"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"


class HypothesisStatus(str, Enum):
    CONFIRMED = "CONFIRMED"
    PROBABLE = "PROBABLE"
    POSSIBLE = "POSSIBLE"
    UNLIKELY = "UNLIKELY"
    INCONCLUSIVE = "INCONCLUSIVE"


class DecisionState(str, Enum):
    ANALYSIS_COMPLETE = "ANALYSIS_COMPLETE"
    ANALYSIS_COMPLETE_WITH_WARNINGS = "ANALYSIS_COMPLETE_WITH_WARNINGS"
    INCONCLUSIVE = "INCONCLUSIVE"
    DATA_INSUFFICIENT = "DATA_INSUFFICIENT"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    ENGINEER_REVIEW_REQUIRED = "ENGINEER_REVIEW_REQUIRED"


class ConfidenceLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INCONCLUSIVE = "INCONCLUSIVE"


class ReviewAction(str, Enum):
    ACCEPT = "ACCEPT"
    MODIFY = "MODIFY"
    REJECT = "REJECT"
    INCONCLUSIVE = "INCONCLUSIVE"
    REQUEST_FIELD_INVESTIGATION = "REQUEST_FIELD_INVESTIGATION"


class BreakerAssessment(str, Enum):
    NORMAL = "NORMAL"
    SLOW = "SLOW"
    FAILED = "FAILED"
    INCONCLUSIVE = "INCONCLUSIVE"


class JobStage(str, Enum):
    UPLOAD = "UPLOAD"
    FILE_DETECTION = "FILE_DETECTION"
    COMTRADE_VALIDATION = "COMTRADE_VALIDATION"
    PARSING = "PARSING"
    SIGNAL_PROCESSING = "SIGNAL_PROCESSING"
    EVENT_RECONSTRUCTION = "EVENT_RECONSTRUCTION"
    PROTECTION_ANALYSIS = "PROTECTION_ANALYSIS"
    CONSISTENCY_CHECKER = "CONSISTENCY_CHECKER"
    FAULT_CLASSIFICATION = "FAULT_CLASSIFICATION"
    RCA = "RCA"
    EVIDENCE = "EVIDENCE"
    REPORT = "REPORT"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"


class SettingApprovalStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class EvidenceSourceType(str, Enum):
    COMTRADE = "COMTRADE"
    RELAY_EVENT_REPORT = "RELAY_EVENT_REPORT"
    BASE_SETTINGS = "BASE_SETTINGS"
    ACTIVE_SETTING = "ACTIVE_SETTING"
    SOE = "SOE"
    SCADA = "SCADA"
    CALCULATION = "CALCULATION"
    PROTECTION_RULE = "PROTECTION_RULE"
    ML_MODEL = "ML_MODEL"
    HISTORICAL_EVENT = "HISTORICAL_EVENT"
